URL_SERVICE = "https://4a90893f-2a57-4b68-a2e5-78c298b09cd5.serverhub.praktikum-services.ru"
DOC_PATH = "/api/logs/main"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits"